### ISSUE TITLE
Upgrade from Jade to Pug

### ISSUE THREAD

**Issue by Cooper-Kunz** [contentful/contentful_express_tutorial#10]
The team behind [Jade](http://jade-lang.com/) realized someone else had the rights to that name. They've since renamed the package during a major version update to [Pug](https://pugjs.org/api/getting-started.html). 

You can read their comments [here](https://github.com/pugjs/pug) about the project's renaming. I'd be happy to submit a PR upgrading this example application to the new package, if that would be helpful?

**Comment by Khaledgarbaya** [comment]
Fixes in https://github.com/contentful/contentful_express_tutorial/pull/13
