### ISSUE TITLE
Error: NODE_EN=development nodemon 

### ISSUE THREAD

**Issue by Samjin** [contentful/contentful_express_tutorial#4]
contentful_express_tutorial@0.0.0 dev C:\works\contentful-node
> NODE_EN=development nodemon ./bin/www

**'NODE_EN' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by Khaledgarbaya** [comment]
Hi @Samjin 
actually, there is two issue in the `package.json`, first `NODE_EN` should be `NODE_ENV` and secondly setting the env variable like that does not work with windows.
I will fix this in https://github.com/contentful/contentful_express_tutorial/pull/5
