### ISSUE TITLE
Heroku app fails to run

### ISSUE THREAD

**Issue by sdellis** [contentful/contentful_express_tutorial#6]
Playing around with Contentful and when I try to deploy to heroku, I get a 503 Application error. `npm run production` seems to generate errors in the heroku logs, but not sure how to resolve it. Can run `npm start` locally  with no problem and can see the app at localhost:3000.

**Comment by axe312ger** [comment]
@sdellis I will have a look :)

**Comment by axe312ger** [comment]
I got it :) Here is my fresh working test: https://ancient-eyrie-62977.herokuapp.com/

The cross-env dependency was listed as devDependency while it was needed for production.
